package full-example:testing;

world example {
    import ariel:wasm-bindings/log-api@0.0.1;
    import ariel:wasm-bindings/rng-api@0.0.1;
//    import ariel:wasm-bindings/udp-api@0.0.1;
    import ariel:wasm-bindings/time-api@0.0.1;

    export do-work: func();

}