[package]
name = "ariel-os-identity"
version = "0.2.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[lib]
harness = false

[dependencies]
ariel-os-embassy-common = { workspace = true }
ariel-os-hal = { workspace = true }

[target.'cfg(context = "ariel-os")'.dev-dependencies]
ariel-os = { path = "../../src/ariel-os" }
ariel-os-boards = { path = "../../src/ariel-os-boards" }

embedded-test = { workspace = true }

[features]
_test = []

[lints]
workspace = true
