name: Git Checks

on:
  pull_request:
  merge_group:

jobs:
  block-fixup:
    if: github.event_name != 'merge_group'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Block Fixup Commit Merge
        uses: 13rac1/block-fixup-merge-action@bd5504fb9ca0253e109d98eb86b7debc01970cdc # v2.0.0

  conventional-commits:
    name: Lint Commits
    if: github.event_name != 'merge_group'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
      - uses: crate-ci/committed@master
