name: PR title checks

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  pr-title:
    name: Lint PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0

      - name: Install committed
        uses: taiki-e/install-action@f63c33fd96cc1e69a29bafd06541cf28588b43a4 # v2
        with:
          tool: committed

      - run: committed --config committed.toml --commit-file <(echo "${PR_TITLE}")
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
